/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7XWfT73X1LW1q4kavwKvMP
// Component: qA8wlj6SPkIX

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Button from "../../Button"; // plasmic-import: SEF-sRmSoqV5c/component
import ActionMenuButton from "../../ActionMenuButton"; // plasmic-import: VNi6NC2QOI/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_plasmic_kit_design_system_deprecated_css from "../plasmic_kit_design_system/plasmic.module.css"; // plasmic-import: tXkSR39sgCDWSitZxC5xFV/projectcss
import plasmic_plasmic_kit_color_tokens_css from "../plasmic_kit_color_tokens/plasmic.module.css"; // plasmic-import: 95xp9cYcv7HrNWpFWWhbcv/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 7XWfT73X1LW1q4kavwKvMP/projectcss
import sty from "./PlasmicPublishButton.module.css"; // plasmic-import: qA8wlj6SPkIX/css

import ArrowRightSvgIcon from "../plasmic_kit_icons/icons/PlasmicIcon__ArrowRightSvg"; // plasmic-import: 9Jv8jb253/icon
import ChevronDownSvgIcon from "../plasmic_kit_icons/icons/PlasmicIcon__ChevronDownSvg"; // plasmic-import: xZrB9_0ir/icon
import PlusSvgIcon from "../plasmic_kit_icons/icons/PlasmicIcon__PlusSvg"; // plasmic-import: sQKgd2GNr/icon

createPlasmicElementProxy;

export type PlasmicPublishButton__VariantMembers = {
  withMenuButton: "withMenuButton";
};
export type PlasmicPublishButton__VariantsArgs = {
  withMenuButton?: SingleBooleanChoiceArg<"withMenuButton">;
};
type VariantPropType = keyof PlasmicPublishButton__VariantsArgs;
export const PlasmicPublishButton__VariantProps = new Array<VariantPropType>(
  "withMenuButton"
);

export type PlasmicPublishButton__ArgsType = {};
type ArgPropType = keyof PlasmicPublishButton__ArgsType;
export const PlasmicPublishButton__ArgProps = new Array<ArgPropType>();

export type PlasmicPublishButton__OverridesType = {
  root?: Flex__<"div">;
  button?: Flex__<typeof Button>;
  menuButton?: Flex__<typeof ActionMenuButton>;
};

export interface DefaultPublishButtonProps {
  withMenuButton?: SingleBooleanChoiceArg<"withMenuButton">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPublishButton__RenderFunc(props: {
  variants: PlasmicPublishButton__VariantsArgs;
  args: PlasmicPublishButton__ArgsType;
  overrides: PlasmicPublishButton__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "withMenuButton",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.withMenuButton
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_plasmic_kit_design_system_deprecated_css.plasmic_tokens,
        plasmic_plasmic_kit_color_tokens_css.plasmic_tokens,
        sty.root,
        {
          [sty.rootwithMenuButton]: hasVariant(
            $state,
            "withMenuButton",
            "withMenuButton"
          )
        }
      )}
    >
      <Button
        data-plasmic-name={"button"}
        data-plasmic-override={overrides.button}
        endIcon={
          <ChevronDownSvgIcon
            className={classNames(projectcss.all, sty.svg__lMfZv)}
            role={"img"}
          />
        }
        size={"small"}
        startIcon={
          <ArrowRightSvgIcon
            className={classNames(projectcss.all, sty.svg__w5R8Q)}
            role={"img"}
          />
        }
        type={["primary"]}
      >
        {"Publish"}
      </Button>
      <ActionMenuButton
        data-plasmic-name={"menuButton"}
        data-plasmic-override={overrides.menuButton}
        className={classNames("__wab_instance", sty.menuButton, {
          [sty.menuButtonwithMenuButton]: hasVariant(
            $state,
            "withMenuButton",
            "withMenuButton"
          )
        })}
        icon={
          <PlusSvgIcon
            className={classNames(projectcss.all, sty.svg__v2UMb)}
            role={"img"}
          />
        }
        size={"small"}
        type={["primary"]}
      >
        {"Publish"}
      </ActionMenuButton>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "button", "menuButton"],
  button: ["button"],
  menuButton: ["menuButton"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  button: typeof Button;
  menuButton: typeof ActionMenuButton;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPublishButton__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPublishButton__VariantsArgs;
    args?: PlasmicPublishButton__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicPublishButton__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicPublishButton__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPublishButton__ArgProps,
          internalVariantPropNames: PlasmicPublishButton__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPublishButton__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPublishButton";
  } else {
    func.displayName = `PlasmicPublishButton.${nodeName}`;
  }
  return func;
}

export const PlasmicPublishButton = Object.assign(
  // Top-level PlasmicPublishButton renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    button: makeNodeComponent("button"),
    menuButton: makeNodeComponent("menuButton"),

    // Metadata about props expected for PlasmicPublishButton
    internalVariantProps: PlasmicPublishButton__VariantProps,
    internalArgProps: PlasmicPublishButton__ArgProps
  }
);

export default PlasmicPublishButton;
/* prettier-ignore-end */
