/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7XWfT73X1LW1q4kavwKvMP
// Component: _LgJk1CxGht_

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Button from "../../Button"; // plasmic-import: SEF-sRmSoqV5c/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_plasmic_kit_design_system_deprecated_css from "../plasmic_kit_design_system/plasmic.module.css"; // plasmic-import: tXkSR39sgCDWSitZxC5xFV/projectcss
import plasmic_plasmic_kit_color_tokens_css from "../plasmic_kit_color_tokens/plasmic.module.css"; // plasmic-import: 95xp9cYcv7HrNWpFWWhbcv/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 7XWfT73X1LW1q4kavwKvMP/projectcss
import sty from "./PlasmicShareButton.module.css"; // plasmic-import: _LgJk1CxGht_/css

import ArrowRightSvgIcon from "../plasmic_kit_icons/icons/PlasmicIcon__ArrowRightSvg"; // plasmic-import: 9Jv8jb253/icon
import ChevronDownSvgIcon from "../plasmic_kit_icons/icons/PlasmicIcon__ChevronDownSvg"; // plasmic-import: xZrB9_0ir/icon

createPlasmicElementProxy;

export type PlasmicShareButton__VariantMembers = {};
export type PlasmicShareButton__VariantsArgs = {};
type VariantPropType = keyof PlasmicShareButton__VariantsArgs;
export const PlasmicShareButton__VariantProps = new Array<VariantPropType>();

export type PlasmicShareButton__ArgsType = {};
type ArgPropType = keyof PlasmicShareButton__ArgsType;
export const PlasmicShareButton__ArgProps = new Array<ArgPropType>();

export type PlasmicShareButton__OverridesType = {
  share?: Flex__<typeof Button>;
};

export interface DefaultShareButtonProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicShareButton__RenderFunc(props: {
  variants: PlasmicShareButton__VariantsArgs;
  args: PlasmicShareButton__ArgsType;
  overrides: PlasmicShareButton__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <Button
      data-plasmic-name={"share"}
      data-plasmic-override={overrides.share}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames("__wab_instance", sty.share)}
      endIcon={
        <ChevronDownSvgIcon
          className={classNames(projectcss.all, sty.svg__mwhzl)}
          role={"img"}
        />
      }
      size={"small"}
      startIcon={
        <ArrowRightSvgIcon
          className={classNames(projectcss.all, sty.svg__kdPqR)}
          role={"img"}
        />
      }
      type={["secondary"]}
    >
      {"Share"}
    </Button>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  share: ["share"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  share: typeof Button;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicShareButton__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicShareButton__VariantsArgs;
    args?: PlasmicShareButton__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicShareButton__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicShareButton__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicShareButton__ArgProps,
          internalVariantPropNames: PlasmicShareButton__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicShareButton__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "share") {
    func.displayName = "PlasmicShareButton";
  } else {
    func.displayName = `PlasmicShareButton.${nodeName}`;
  }
  return func;
}

export const PlasmicShareButton = Object.assign(
  // Top-level PlasmicShareButton renders the root element
  makeNodeComponent("share"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicShareButton
    internalVariantProps: PlasmicShareButton__VariantProps,
    internalArgProps: PlasmicShareButton__ArgProps
  }
);

export default PlasmicShareButton;
/* prettier-ignore-end */
